### ISSUE TITLE
RGB

### ISSUE THREAD

**Issue by zeffamedia** [groundmelon/m100_x3#4]
Hi 
Has RGB been added, or is the o/p still in gray scale ?

**Comment by groundmelon** [comment]
For "Manully Launched ROS Driver", there is a ros parameter called "enable_color", which can make it output RGB image.

For the client and server type, it is not compatible with RGB, and I have no plan to add RGB into it since I no longer use Manifold + X3 any more, and have no hardware to test it.

However, it is very simple to modified it to a RGB version if you don't want to keep it compatible with gray scale ones. Just change the buffer size to 3x, memcpy original data into it, and change the corresponding client code.
